name: Cppcheck on PR Diff

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - name: Install cppcheck
        run: sudo apt-get install cppcheck -y

      - name: Fetch latest changes from origin
        run: git fetch origin

      - name: Find changed C++ files
        id: find-files
        run: |
          echo "Finding changed C++ files..."
          echo "cpp_files=$(git diff --name-only origin/${{ github.base_ref }}... -- '*.cpp' '*.h' | tr '\n' ' '))" >> $GITHUB_ENV
        
      - name: Run cppcheck on modified files
        if: ${{ steps.find-files.outputs.cpp_files != '' }}
        run: |
          echo "Running cppcheck on modified files..."
          cppcheck --enable=all --error-exitcode=1 --force --inline-suppr --quiet ${{ steps.find-files.outputs.cpp_files }}
